### ISSUE TITLE
random factor

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#103]
you cannot set up the random factor to 0
it defaults back to 50
![eb19ec9685962111caa503c11fff60b1](https://user-images.githubusercontent.com/26008574/50218481-c7953b80-0394-11e9-9ac6-5d16056dc473.png)

**Comment by giucu91** [comment]
Random factor is working, it's referring to mix the sizes of the images in creative grid. The one not working is shuffle.
