### ISSUE TITLE
Images shift up and down

### ISSUE THREAD

**Issue by themainframech** [MachoThemes/modula-lite#108]
Please see video for reference: https://www.dropbox.com/s/i3sv0sm02mee94w/modula%20bug.mov?dl=0

**Comment by razvanaldea89** [comment]
Can confirm this happens. 
![modula resizer bug](https://user-images.githubusercontent.com/44024114/63415751-daba4880-c406-11e9-8be8-01211d0b49b7.PNG)

**Comment by razvanaldea89** [comment]
There is another commit that fixes this issue along with other issues. Please see #232
