### ISSUE TITLE
GIFs only appear animated in lightbox

### ISSUE THREAD

**Issue by themainframech** [MachoThemes/modula-lite#110]
Please see the following gallery for reference:

https://wp-modula.com/gif-gallery

**Comment by giucu91** [comment]
+1

**Comment by razvanaldea89** [comment]
Serving non resized GIFs is a solution, will work both on "thumbnails" view and lightbox. And could implement an option for resizing GIFs ( with no animation ) if the user has lots of them in the gallery and wants to speed up the process.

@giucu91 @cristianraiber @andrei-l-cristea  any thoughts on this ideea?

**Comment by cristianraiber** [comment]
I think we need to look into ways we can serve animated GIFs without compromising on the "animation" part. That's what makes it a GIF, after all.

**Comment by razvanaldea89** [comment]
Moved this to 2.2.4. It has a "fix" there which enables animation on "thumbnail"

**Comment by giucu91** [comment]
We will wait for WP Core to resolve this issue.
