### ISSUE TITLE
Wrong text-domain + re-generate .po files

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#126]
includes/admin/class-modula-addons.php
[L61]  esc_html__  Incorrect text domain used ("modula-gallery")
[L72]  esc_html__  Incorrect text domain used ("modula-gallery")
[L73]  esc_html__  Incorrect text domain used ("modula-gallery")
[L77]  esc_html__  Incorrect text domain used ("modula-gallery")

includes/admin/class-modula-admin.php
[L24]  __          Incorrect text domain used ("modula-lite")
[L24]  __          Incorrect text domain used ("modula-lite")
[L25]  __          Incorrect text domain used ("modula-lite")
[L25]  __          Incorrect text domain used ("modula-lite")
[L32]  esc_html__  Incorrect text domain used ("modula-lite")

includes/admin/class-modula-cpt-fields-helper.php
[L10]   esc_html__  Missing text domain
[L13]   esc_html__  Missing text domain
[L16]   esc_html__  Missing text domain
[L19]   esc_html__  Missing text domain
[L22]   esc_html__  Missing text domain
[L25]   esc_html__  Missing text domain
[L28]   esc_html__  Missing text domain
[L33]   esc_html__  Incorrect text domain used ("modula-gallery")
[L34]   esc_html__  Incorrect text domain used ("modula-gallery")
[L40]   esc_html__  Incorrect text domain used ("modula-gallery")
[L41]   esc_html__  Incorrect text domain used ("modula-gallery")
[L47]   esc_html__  Incorrect text domain used ("modula-gallery")
[L48]   esc_html__  Incorrect text domain used ("modula-gallery")
[L54]   esc_html__  Incorrect text domain used ("modula-gallery")
[L55]   esc_html__  Incorrect text domain used ("modula-gallery")
[L61]   esc_html__  Incorrect text domain used ("modula-gallery")
[L62]   esc_html__  Incorrect text domain used ("modula-gallery")
[L68]   esc_html__  Incorrect text domain used ("modula-gallery")
[L69]   esc_html__  Incorrect text domain used ("modula-gallery")
[L74]   esc_html__  Incorrect text domain used ("modula-gallery")
[L75]   esc_html__  Incorrect text domain used ("modula-gallery")
[L81]   esc_html__  Incorrect text domain used ("modula-gallery")
[L82]   esc_html__  Incorrect text domain used ("modula-gallery")
[L93]   esc_html__  Incorrect text domain used ("modula-gallery")
[L93]   esc_html__  Incorrect text domain used ("modula-gallery")
[L93]   esc_html__  Incorrect text domain used ("modula-gallery")
[L104]  esc_html__  Incorrect text domain used ("modula-gallery")
[L106]  esc_html__  Incorrect text domain used ("modula-gallery")
[L109]  esc_html__  Incorrect text domain used ("modula-gallery")
[L110]  esc_html__  Incorrect text domain used ("modula-gallery")
[L125]  esc_html__  Incorrect text domain used ("modula-gallery")
[L135]  esc_html__  Incorrect text domain used ("modula-gallery")
[L137]  esc_html__  Incorrect text domain used ("modula-gallery")
[L142]  esc_html__  Incorrect text domain used ("modula-gallery")
[L144]  esc_html__  Incorrect text domain used ("modula-gallery")
[L149]  esc_html__  Incorrect text domain used ("modula-gallery")
[L152]  esc_html__  Incorrect text domain used ("modula-gallery")
[L156]  esc_html__  Incorrect text domain used ("modula-gallery")
[L159]  esc_html__  Incorrect text domain used ("modula-gallery")
[L163]  esc_html__  Incorrect text domain used ("modula-gallery")
[L165]  esc_html__  Incorrect text domain used ("modula-gallery")
[L173]  esc_html__  Incorrect text domain used ("modula-gallery")
[L175]  esc_html__  Incorrect text domain used ("modula-gallery")
[L178]  esc_html__  Incorrect text domain used ("modula-gallery")
[L179]  esc_html__  Incorrect text domain used ("modula-gallery")
[L180]  esc_html__  Incorrect text domain used ("modula-gallery")
[L181]  esc_html__  Incorrect text domain used ("modula-gallery")
[L183]  esc_html__  Incorrect text domain used ("modula-gallery")
[L184]  esc_html__  Incorrect text domain used ("modula-gallery")
[L188]  esc_html__  Incorrect text domain used ("modula-gallery")
[L190]  esc_html__  Incorrect text domain used ("modula-gallery")
[L191]  esc_html__  Incorrect text domain used ("modula-gallery")
[L192]  esc_html__  Incorrect text domain used ("modula-gallery")
[L193]  esc_html__  Incorrect text domain used ("modula-gallery")
[L194]  esc_html__  Incorrect text domain used ("modula-gallery")
[L200]  esc_html__  Incorrect text domain used ("modula-gallery")
[L203]  esc_html__  Incorrect text domain used ("modula-gallery")
[L209]  esc_html__  Incorrect text domain used ("modula-gallery")
[L211]  esc_html__  Incorrect text domain used ("modula-gallery")
[L216]  esc_html__  Incorrect text domain used ("modula-gallery")
[L218]  __          Incorrect text domain used ("modula-gallery")
[L220]  esc_html__  Incorrect text domain used ("modula-gallery")
[L221]  esc_html__  Incorrect text domain used ("modula-gallery")
[L222]  esc_html__  Incorrect text domain used ("modula-gallery")
[L227]  esc_html__  Incorrect text domain used ("modula-gallery")
[L229]  __          Incorrect text domain used ("modula-gallery")
[L231]  esc_html__  Incorrect text domain used ("modula-gallery")
[L232]  esc_html__  Incorrect text domain used ("modula-gallery")
[L233]  esc_html__  Incorrect text domain used ("modula-gallery")
[L234]  esc_html__  Incorrect text domain used ("modula-gallery")
[L239]  esc_html__  Incorrect text domain used ("modula-gallery")
[L242]  esc_html__  Incorrect text domain used ("modula-gallery")
[L246]  esc_html__  Incorrect text domain used ("modula-gallery")
[L249]  esc_html__  Incorrect text domain used ("modula-gallery")
[L253]  esc_html__  Incorrect text domain used ("modula-gallery")
[L258]  esc_html__  Incorrect text domain used ("modula-gallery")
[L262]  esc_html__  Incorrect text domain used ("modula-gallery")
[L267]  esc_html__  Incorrect text domain used ("modula-gallery")
[L273]  esc_html__  Incorrect text domain used ("modula-gallery")
[L280]  esc_html__  Incorrect text domain used ("modula-gallery")
[L287]  esc_html__  Incorrect text domain used ("modula-gallery")
[L294]  esc_html__  Incorrect text domain used ("modula-gallery")
[L300]  esc_html__  Incorrect text domain used ("modula-gallery")
[L309]  esc_html__  Incorrect text domain used ("modula-gallery")
[L310]  esc_html__  Incorrect text domain used ("modula-gallery")
[L320]  esc_html__  Incorrect text domain used ("modula-gallery")
[L328]  esc_html__  Incorrect text domain used ("modula-gallery")
[L337]  esc_html__  Incorrect text domain used ("modula-gallery")
[L346]  esc_html__  Incorrect text domain used ("modula-gallery")
[L353]  esc_html__  Incorrect text domain used ("modula-gallery")
[L362]  esc_html__  Incorrect text domain used ("modula-gallery")
[L371]  esc_html__  Incorrect text domain used ("modula-gallery")
[L374]  esc_html__  Incorrect text domain used ("modula-gallery")
[L380]  esc_html__  Incorrect text domain used ("modula-gallery")
[L383]  esc_html__  Incorrect text domain used ("modula-gallery")

includes/admin/class-modula-cpt.php
[L21]  _x          Incorrect text domain used ("text_domain")
[L22]  _x          Incorrect text domain used ("text_domain")
[L23]  __          Incorrect text domain used ("text_domain")
[L24]  __          Incorrect text domain used ("text_domain")
[L25]  __          Incorrect text domain used ("text_domain")
[L26]  __          Incorrect text domain used ("text_domain")
[L27]  __          Incorrect text domain used ("text_domain")
[L28]  __          Incorrect text domain used ("text_domain")
[L29]  __          Incorrect text domain used ("text_domain")
[L30]  __          Incorrect text domain used ("text_domain")
[L31]  __          Incorrect text domain used ("text_domain")
[L32]  __          Incorrect text domain used ("text_domain")
[L33]  __          Incorrect text domain used ("text_domain")
[L34]  __          Incorrect text domain used ("text_domain")
[L35]  __          Incorrect text domain used ("text_domain")
[L36]  __          Incorrect text domain used ("text_domain")
[L37]  __          Incorrect text domain used ("text_domain")
[L38]  __          Incorrect text domain used ("text_domain")
[L39]  __          Incorrect text domain used ("text_domain")
[L40]  __          Incorrect text domain used ("text_domain")
[L41]  __          Incorrect text domain used ("text_domain")
[L42]  __          Incorrect text domain used ("text_domain")
[L43]  __          Incorrect text domain used ("text_domain")
[L44]  __          Incorrect text domain used ("text_domain")
[L45]  __          Incorrect text domain used ("text_domain")
[L46]  __          Incorrect text domain used ("text_domain")
[L47]  __          Incorrect text domain used ("text_domain")
[L51]  __          Incorrect text domain used ("text_domain")
[L52]  __          Incorrect text domain used ("text_domain")
[L69]  esc_html__  Incorrect text domain used ("text_domain")
[L74]  esc_html__  Incorrect text domain used ("text_domain")
[L79]  esc_html__  Incorrect text domain used ("text_domain")

includes/admin/class-modula-field-builder.php
[L98]   __          Incorrect text domain used ("text-domain")
[L124]  esc_html__  Incorrect text domain used ("modula-gallery")
[L169]  esc_html__  Incorrect text domain used ("modula-gallery")
[L307]  esc_html__  Incorrect text domain used ("modula-gallery")
[L308]  esc_html__  Incorrect text domain used ("modula-gallery")
[L311]  esc_html__  Incorrect text domain used ("modula-gallery")
[L312]  esc_html__  Incorrect text domain used ("modula-gallery")
[L313]  esc_html__  Incorrect text domain used ("modula-gallery")
[L314]  esc_html__  Incorrect text domain used ("modula-gallery")
[L315]  esc_html__  Incorrect text domain used ("modula-gallery")
[L316]  esc_html__  Incorrect text domain used ("modula-gallery")
[L317]  esc_html__  Incorrect text domain used ("modula-gallery")
[L318]  esc_html__  Incorrect text domain used ("modula-gallery")
[L319]  esc_html__  Incorrect text domain used ("modula-gallery")
[L320]  esc_html__  Incorrect text domain used ("modula-gallery")
[L321]  esc_html__  Incorrect text domain used ("modula-gallery")
[L329]  esc_html__  Incorrect text domain used ("modula-gallery")
[L338]  esc_html__  Incorrect text domain used ("modula-gallery")
[L353]  esc_html__  Incorrect text domain used ("modula-gallery")
[L354]  esc_html__  Incorrect text domain used ("modula-gallery")
[L355]  esc_html__  Incorrect text domain used ("modula-gallery")

includes/admin/class-modula-image.php
[L55]   __  Incorrect text domain used ("modula-gallery")
[L75]   __  Incorrect text domain used ("modula-gallery")
[L95]   __  Incorrect text domain used ("modula-gallery")
[L100]  __  Incorrect text domain used ("modula-gallery")
[L108]  __  Incorrect text domain used ("modula-gallery")
[L120]  __  Incorrect text domain used ("modula-gallery")
[L240]  __  Incorrect text domain used ("modula-gallery")

includes/admin/class-modula-upsells.php
[L30]  esc_html__  Incorrect text domain used ("modula-gallery")
[L31]  esc_html__  Incorrect text domain used ("modula-gallery")
[L40]  esc_html__  Incorrect text domain used ("modula-gallery")
[L41]  esc_html__  Incorrect text domain used ("modula-gallery")
[L50]  esc_html__  Incorrect text domain used ("modula-gallery")
[L51]  esc_html__  Incorrect text domain used ("modula-gallery")
[L61]  esc_html__  Incorrect text domain used ("modula-gallery")
[L62]  esc_html__  Incorrect text domain used ("modula-gallery")
[L72]  esc_html__  Incorrect text domain used ("modula-gallery")
[L73]  esc_html__  Incorrect text domain used ("modula-gallery")
[L84]  esc_html__  Incorrect text domain used ("modula-lite")

includes/admin/modula-js-templates.php
[L29]   esc_html_e  Incorrect text domain used ("modula-gallery")
[L30]   esc_html_e  Incorrect text domain used ("modula-gallery")
[L33]   _e          Incorrect text domain used ("modula-gallery")
[L53]   esc_html_e  Incorrect text domain used ("modula-gallery")
[L56]   _e          Incorrect text domain used ("modula-gallery")
[L63]   esc_html_e  Incorrect text domain used ("modula-gallery")
[L66]   _e          Incorrect text domain used ("modula-gallery")
[L72]   esc_html_e  Incorrect text domain used ("modula-gallery")
[L80]   esc_html_e  Incorrect text domain used ("modula-gallery")
[L82]   esc_html_e  Incorrect text domain used ("modula-gallery")
[L83]   esc_html_e  Incorrect text domain used ("modula-gallery")
[L84]   esc_html_e  Incorrect text domain used ("modula-gallery")
[L87]   esc_html_e  Incorrect text domain used ("modula-gallery")
[L88]   esc_html_e  Incorrect text domain used ("modula-gallery")
[L89]   esc_html_e  Incorrect text domain used ("modula-gallery")
[L96]   esc_html_e  Incorrect text domain used ("modula-gallery")
[L99]   _e          Incorrect text domain used ("modula-gallery")
[L105]  esc_html_e  Incorrect text domain used ("modula-gallery")
[L118]  esc_attr_e  Incorrect text domain used ("modula-gallery")
[L119]  esc_html_e  Incorrect text domain used ("modula-gallery")
[L125]  _e          Incorrect text domain used ("modula-gallery")

includes/admin/tabs/addons.php
[L2]  _e  Incorrect text domain used ("modula-lite")
[L3]  _e  Incorrect text domain used ("modula-lite")
[L4]  _e  Incorrect text domain used ("modula-lite")

includes/admin/tabs/modula.php
[L2]  _e  Incorrect text domain used ("modula-lite")
[L3]  _e  Incorrect text domain used ("modula-lite")
[L4]  _e  Incorrect text domain used ("modula-lite")

includes/admin/tabs/upsell.php
[L11]  esc_html__  Incorrect text domain used ("modula-lite")
[L12]  esc_html__  Incorrect text domain used ("modula-lite")
[L17]  esc_html__  Incorrect text domain used ("modula-lite")
[L18]  esc_html__  Incorrect text domain used ("modula-lite")
[L23]  esc_html__  Incorrect text domain used ("modula-lite")
[L24]  esc_html__  Incorrect text domain used ("modula-lite")
[L29]  esc_html__  Incorrect text domain used ("modula-lite")
[L30]  esc_html__  Incorrect text domain used ("modula-lite")
[L35]  esc_html__  Incorrect text domain used ("modula-lite")
[L36]  esc_html__  Incorrect text domain used ("modula-lite")
[L41]  esc_html__  Incorrect text domain used ("modula-lite")
[L42]  esc_html__  Incorrect text domain used ("modula-lite")
[L47]  esc_html__  Incorrect text domain used ("modula-lite")
[L48]  esc_html__  Incorrect text domain used ("modula-lite")
[L60]  _e          Incorrect text domain used ("modula-lite")
[L61]  _e          Incorrect text domain used ("modula-lite")
[L84]  _e          Incorrect text domain used ("modula-lite")

includes/class-modula-upgrades.php
[L14]   esc_html__  Incorrect text domain used ("modula-lite")
[L18]   esc_html__  Incorrect text domain used ("modula-lite")
[L146]  esc_html__  Incorrect text domain used ("modula")
[L147]  esc_html__  Incorrect text domain used ("modula")
[L148]  esc_html__  Incorrect text domain used ("modula")
[L152]  esc_html__  Missing text domain
[L276]  __          Incorrect text domain used ("modula")
[L284]  __          Incorrect text domain used ("modula")
[L303]  __          Incorrect text domain used ("modula")

includes/class-modula.php
[L57]   __  Incorrect text domain used ("modula-gallery")
[L58]   __  Incorrect text domain used ("modula-gallery")
[L59]   __  Incorrect text domain used ("modula-gallery")
[L60]   __  Incorrect text domain used ("modula-gallery")
[L129]  __  Incorrect text domain used ("modula-gallery")

includes/libraries/class-modula-feedback.php
[L57]   esc_html__  Incorrect text domain used ("modula-gallery")
[L61]   __          Incorrect text domain used ("modula-gallery")
[L62]   __          Incorrect text domain used ("modula-gallery")
[L62]   __          Incorrect text domain used ("modula-gallery")
[L140]  __          Incorrect text domain used ("modula-gallery")
[L141]  __          Incorrect text domain used ("modula-gallery")
[L142]  __          Incorrect text domain used ("modula-gallery")
[L143]  __          Incorrect text domain used ("modula-gallery")
[L144]  __          Incorrect text domain used ("modula-gallery")
[L208]  __          Incorrect text domain used ("modula-gallery")
[L211]  __          Incorrect text domain used ("modula-gallery")
[L212]  __          Incorrect text domain used ("modula-gallery")
[L213]  __          Incorrect text domain used ("modula-gallery")
[L214]  __          Incorrect text domain used ("modula-gallery")
[L215]  __          Missing text domain

includes/libraries/class-modula-review.php
[L22]  __  Incorrect text domain used ("modula-gallery")
[L23]  __  Incorrect text domain used ("modula-gallery")
[L24]  __  Incorrect text domain used ("modula-gallery")
[L25]  __  Incorrect text domain used ("modula-gallery")

includes/public/class-modula-shortcode.php
[L51]   esc_html__  Incorrect text domain used ("modula-gallery")
[L74]   esc_html__  Incorrect text domain used ("modula-gallery")
[L88]   esc_html__  Incorrect text domain used ("modula-gallery")
[L100]  esc_html__  Incorrect text domain used ("modula-gallery")
Warning: 256 problems Use --force to continue.

**Comment by giucu91** [comment]
This is from an old version.
