### ISSUE TITLE
Blue bottom border on "creative gallery"

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#136]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/7841556/53234895-3e063080-3699-11e9-864d-8825da2ef7a4.png">

---

This is normally used in the Custom Grid to place the toggle "Grid Helper"

**Comment by giucu91** [comment]
This should be implemented only on lite because in pro we have Bulk edit.

**Comment by giucu91** [comment]
With PRO the blue bar it is hidden.

**Comment by andyluak** [comment]
Modula Lite 2.3.1 si Pro 2.3.0 , works .  @giucu91

**Comment by razvanaldea89** [comment]
Seems ok
