### ISSUE TITLE
Add an option to remove all DB entries on plugin uninstall

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#154]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/7841556/54472837-0857f180-47d8-11e9-969a-1f83f8382783.png">

**Comment by cristianraiber** [comment]
^ has to be opt-in

**Comment by razvanaldea89** [comment]
There are currently 3 options prepared:
- Delete options 
- Delete transients
- Delete custom post type and it's meta

**Comment by andyluak** [comment]
Tested . It might be a better ussage to use CANNOT instead of CAN NOT in the warning :  CAUTION. THIS CAN NOT BE UNDONE!

**Comment by cristianraiber** [comment]
@razvanaldea89 - @andyluak has a good point above :)
