### ISSUE TITLE
Re-word 'Update' button to say 'Save gallery'

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#156]
A lot of users don't realise that the update button is what will actually save the gallery

**Comment by cristianraiber** [comment]
Should also change the metabox title from "publish" to "Save/Update Gallery". 

I also think we can safely remove the metabox's content almost entirely ... @giucu91 - thoughts?

<img width="303" alt="image" src="https://user-images.githubusercontent.com/7841556/72512579-c9aa2200-3854-11ea-8fc2-03fc6c86fa59.png">

I am referring to Status & Published ... this is functionality related to blog posts and not to galleries.

**Comment by razvanaldea89** [comment]
Maybe it is better if we don't rename the button if the gallery hasn't been published, so the 'Publish' button remains. The renaming might confuse the user when creating a new gallery.

**Comment by cristianraiber** [comment]
@razvanaldea89 - this idea is actually really good :) @andyluak - can you please make the necessary changes?

**Comment by andyluak** [comment]
@cristianraiber changing it now

**Comment by andrei-l-cristea** [comment]
This is working properly, when you first create the gallery you have the option to `Publish`, then after the first save the label is changed to `Update gallery`.
