### ISSUE TITLE
Lightbox2 doesn't work with Salient theme

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#159]
More details here: https://wordpress.org/support/topic/hit-and-miss-8/

**Comment by razvanaldea89** [comment]
Can't replicate issue either and given link gives page not found

**Comment by razvanaldea89** [comment]
But a thing that I found with this theme is that the arrow navigation is affected on MagnificPopup

**Comment by giucu91** [comment]
We will drop support for lightbox2
