### ISSUE TITLE
WPML integration.

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/modula-lite#16]
On any other language than the default one the number of images will be doubled and the gallery's grid will be messed up.

**Comment by darfil81** [comment]
Any update? WPML is the most used plugin for multilanguage wordpress websites.
I am forced to swtitch to another plugin for all ou websites if the bug persists.

**Comment by giucu91** [comment]
Hello @darfil81,

Can you please give us access to your WordPress installation in order to test a fix about this problem? Please send it to hello@wp-modula.com.

Thank you,
George

**Comment by darfil81** [comment]
HI George,
    do you need an ftp account or only an access to wordpress
      administration panel?
    thank you
    
    
      
      Documento senza titolo
      
BODY {font-family:"Trebuchet MS", Arial, Helvetica, sans-serif;font-size:14px}
#container {margin-top:30px;font-family:"Trebuchet MS", Arial, Helvetica, sans-serif;font-size:12px;color:#000000}
b {font-size:14px}
#recapiti {font-size:11px}
#privacy {font-size:10px}

      
        Dario Filizzola
        Web designer / Web developer
        
        
        
          VoIP tel: +39 0916199351
          URL: http://www.os2.it
        
        Le informazioni trasmesse sono destinate
          esclusivamente alla persona o alla società in indirizzo e sono
          da intendersi confidenziali e riservate. Ogni trasmissione,
          inoltro, diffusione o altro uso di queste informazioni a
          persone o società differenti dal destinatario é proibita. Se
          ricevete questa comunicazione per errore, contattate il
          mittente e cancellate le informazioni da ogni computer. 
          The information transmitted is intended only for the person or
          entity to which it is addressed and may contain confidential
          and/or privileged material. Any review, retransmission,
          dissemination or other use of, or taking of any action in
          reliance upon, this information by persons or entities other
          than the intended recipient is prohibited. If you received
          this in error, please contact the sender and delete the
          material from any computer. 
      
    
    Il 29/09/2017 11.39, George Ciobanu ha
      scritto:
    
    
      Hello @darfil81,
      Can you please give us access to your WordPress installation in
        order to test a fix about this problem? Please send it to hello@wp-modula.com.
      Thank you,
        George
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MachoThemes/modula-lite","title":"MachoThemes/modula-lite","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MachoThemes/modula-lite"}},"updates":{"snippets":[{"icon":"PERSON","message":"@giucu91 in #16: Hello @darfil81,\r\n\r\nCan you please give us access to your WordPress installation in order to test a fix about this problem? Please send it to hello@wp-modula.com.\r\n\r\nThank you,\r\nGeorge"}],"action":{"name":"View Issue","url":"https://github.com/MachoThemes/modula-lite/issues/16#issuecomment-333081044"}}}</scr
 ipt>
</body>
</html>
</html>

**Comment by cristianraiber** [comment]
@darfil81 - please send both to hello@wp-modula.com

Thanks,
Cristian.

**Comment by darfil81** [comment]
-- Please reply above this line --


Hi Dario,

please provide both.

Thanks,
Cristian.

 How easy was it to get the help you needed today? 
 Very Easy [1]    Easy [2]    Not Easy [3]

--
Cristian Raiber
hello@wp-modula.com


Links:
------
[1]
https://secure.helpscout.net/satisfaction/135901569/record/1192767544/1/
[2]
https://secure.helpscout.net/satisfaction/135901569/record/1192767544/2/
[3]
https://secure.helpscout.net/satisfaction/135901569/record/1192767544/3/

**Comment by darfil81** [comment]
Hi Cristian,
    you can access to view website:
    http://www.suitepalermo.it/os2login
    
    user: modula
      password: 73(8(4O7jrwvgPgICJKnXxK#
    FTP: ftp.chiffare.it
      Username: modula@suitepalermo.it
      Password: modulaSuite!
    Thank you.
      
    
      
      Documento senza titolo
      
BODY {font-family:"Trebuchet MS", Arial, Helvetica, sans-serif;font-size:14px}
#container {margin-top:30px;font-family:"Trebuchet MS", Arial, Helvetica, sans-serif;font-size:12px;color:#000000}
b {font-size:14px}
#recapiti {font-size:11px}
#privacy {font-size:10px}

      
        Dario Filizzola
        Web designer / Web developer
        
        
        
          VoIP tel: +39 0916199351
          URL: http://www.os2.it
        
        Le informazioni trasmesse sono destinate
          esclusivamente alla persona o alla società in indirizzo e sono
          da intendersi confidenziali e riservate. Ogni trasmissione,
          inoltro, diffusione o altro uso di queste informazioni a
          persone o società differenti dal destinatario é proibita. Se
          ricevete questa comunicazione per errore, contattate il
          mittente e cancellate le informazioni da ogni computer. 
          The information transmitted is intended only for the person or
          entity to which it is addressed and may contain confidential
          and/or privileged material. Any review, retransmission,
          dissemination or other use of, or taking of any action in
          reliance upon, this information by persons or entities other
          than the intended recipient is prohibited. If you received
          this in error, please contact the sender and delete the
          material from any computer. 
      
    
    Il 29/09/2017 13.27, Modula ha scritto:
    
    
      
      
         Hi Dario,
          
          please provide both.
          
          Thanks,
          Cristian.
          
          
          How easy was it to get the help you needed today?
          
          Very Easy
             Easy    Not Easy
          
          --
          Cristian Raiber
          hello@wp-modula.com
        
        {#HS:440537089-7810#}  
      
       On Fri,
        Sep 29, 2017 at 12:59:18 EEST, Dario Filizzola - Os2
        <dario@os2.it> wrote:
        
          
            HI George,
            do you need an ftp account or only an access to wordpress
              administration panel?
            thank you
            
            Dario Filizzola
              Web designer / Web developer
              
              
              VoIP tel: +39 0916199351
                URL: http://www.os2.it
              Le informazioni trasmesse sono destinate
                esclusivamente alla persona o alla società in indirizzo
                e sono da intendersi confidenziali e riservate. Ogni
                trasmissione, inoltro, diffusione o altro uso di queste
                informazioni a persone o società differenti dal
                destinatario é proibita. Se ricevete questa
                comunicazione per errore, contattate il mittente e
                cancellate le informazioni da ogni computer.
                The information transmitted is intended only for the
                person or entity to which it is addressed and may
                contain confidential and/or privileged material. Any
                review, retransmission, dissemination or other use of,
                or taking of any action in reliance upon, this
                information by persons or entities other than the
                intended recipient is prohibited. If you received this
                in error, please contact the sender and delete the
                material from any computer.
            
            Il 29/09/2017 11.39, George
              Ciobanu ha scritto:
            
            
              Hello @darfil81,
              Can you please give us access to your WordPress
                installation in order to test a fix about this problem?
                Please send it to hello@wp-modula.com.
              Thank you,
                George
              -

**Comment by giucu91** [comment]
The function get_posts doesn't filter the posts by language and this function will return all posts from all languages and this is what causes the issue.
