### ISSUE TITLE
title and caption show html

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#163]
the mobile version and the HTML is showing when viewing the image full screen, #4 is the desktop version and the HTML is functioning, but when hovering over the text, HTML appears
<img width="1440" alt="4" src="https://user-images.githubusercontent.com/26008574/55322021-c8edfe00-5483-11e9-826d-8f68d54df7e5.png">
![3](https://user-images.githubusercontent.com/26008574/55322024-c8edfe00-5483-11e9-8250-85e465a92fa7.png)

**Comment by razvanaldea89** [comment]
On title hover it still shows HTML ( when html is entered in media title )
