### ISSUE TITLE
export/import issue

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#168]
does not work to import a gallery - the images appear blank in the gallery

**Comment by razvanaldea89** [comment]
When importing from version 2.0.7 to 2.0.8 importer gives undefined offset in modula-best-grid-gallery\includes\admin\class-modula-importer-exporter.php on lines 164 and 165.

**Comment by giucu91** [comment]
You need to export from 2.0.8 in order to test it. But test again also with 2.0.7 export to check for error

**Comment by razvanaldea89** [comment]
2.0.8 to 2.0.8 works.
