### ISSUE TITLE
Filtru

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/modula-lite#174]
https://github.com/MachoThemes/modula-lite/blob/2.0.8/includes/public/templates/modula-gallery.php#L1-L5

In loc de asta ar trebui pus https://gist.github.com/giucu91/7dd083ed0c011c223fb05e1863591ebd

E mai usor de inteles si asa filtru filtreaza toate clasele nu doar pe cele noi.

**Comment by razvanaldea89** [comment]
Has commit https://github.com/MachoThemes/modula-lite/commit/d8f609530144e8df350b48a6754a3c583a39d644
