### ISSUE TITLE
Elementor, Beaver Builder, SiteOrigin, Brizy

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#182]
We need blocks for all the above.

**Comment by giucu91** [comment]
@cristianraiber should we close this issue ?

**Comment by cristianraiber** [comment]
It looks like we're missing a Brizy integration but not a lot of people are using it anyway so, yeah. Closing it for now. 

Note: We should also look into integrating with Oxygen builder. Seems semi-popular as well.
