### ISSUE TITLE
Add WhatsApp as social sharing network

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#195]

**Comment by andyluak** [comment]
Tested myself , needs testing from others .

**Comment by razvanaldea89** [comment]
Moved to 2.2.4 because it has already been implemented in 2.2.4 branch

**Comment by cristianraiber** [comment]
👏

**Comment by andrei-l-cristea** [comment]
tested this, but the image is not shared in whatsapp or web.whatsapp. I only get the title of the page. Can someone else test this as well?

**Comment by razvanaldea89** [comment]
Should have a fix for both missing image and js bug on click

**Comment by cristianraiber** [comment]
Tested this and it now works as it should.
