### ISSUE TITLE
Loading effect issue

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#198]
Loading effect - i set everything to "0" but the gallery  images still appearing with a zooming effect.

**Comment by razvanaldea89** [comment]
Think scale has to be set to 100 so that no zooming effect will be present on loading

**Comment by mplusb** [comment]
works like this. Maybe mentioned somewhere that for no effect needs to be 100?

**Comment by razvanaldea89** [comment]
Yes, it mentions that it makes an effect if above or below 100. Maybe we should also mention that 100 gives no effect.
![modula loading effect](https://user-images.githubusercontent.com/44024114/63505113-99479d00-c4db-11e9-8415-f0cef6370582.PNG)
