### ISSUE TITLE
Minor problem with the logo on the extensions page

### ISSUE THREAD

**Issue by razvanaldea89** [MachoThemes/modula-lite#199]
![modula lite extensions](https://user-images.githubusercontent.com/44024114/60273345-9cb91080-98fe-11e9-9f03-d0e7f516cfcf.PNG)

**Comment by cristianraiber** [comment]
@giucu91 - this ain't minor

**Comment by cristian-e** [comment]
should be fixed now

**Comment by giucu91** [comment]
It is resolved.
