### ISSUE TITLE
Feature Request: Keeping the original image aspect ratio

### ISSUE THREAD

**Issue by rasedulhasan** [MachoThemes/modula-lite#200]
Make the 12 helper grids smaller in size, so it is possible to keep the aspect ratio of the images more accurate. 

Add a setting to set the helper grid size.

Add an option to keep the original aspect ratio of the images, probably by pressing CTRL+Dragging can do that?

Thanks!

**Comment by cristianraiber** [comment]
@rasedulhasan - so sorry for the late reply on this one, but we already have this exact feature. Holding down ctrl/cmd+d keeps image ratios intact, when using the custom grid.
