### ISSUE TITLE
not all galleries show in Modula’s elementor block

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#208]

**Comment by razvanaldea89** [comment]
Could you please give more info? Tested with 5 galleries and seems to work, all are displayed

**Comment by mplusb** [comment]
in the drop-down when you click to select a gallery not all of them are displayed there.
Screenshot: https://gyazo.com/6e645bc372ab65c45c08541bf8c7e2f2
And how many galleries I have: https://gyazo.com/7540579fad56c35c71e8ea79629c5525

**Comment by razvanaldea89** [comment]
Confirmed bug

**Comment by giucu91** [comment]
Fixed in 2.1.6

**Comment by cristianraiber** [comment]
@giucu91 @razvanaldea89 - just a quick question here:

https://github.com/MachoThemes/modula-lite/commit/2939f206d6d68e189c1dc4548bc48500ab427c1b#diff-2a499340e59f8a21a87dfd34e557c146R141

It looks like you're pulling ALL galleries inside your query ... My question is: how will this affect performance if the user has, let's say, 200-500 galleries?

**Comment by giucu91** [comment]
@cristianraiber it will be slow.

@razvanaldea89 we need to find a way to add options there via ajax, or create a custom control that should add galleries with ajax.

**Comment by cristianraiber** [comment]
Related; https://github.com/MachoThemes/modula-lite/tree/elementor-widget-ajax-search
