### ISSUE TITLE
small empty space on the right of the gallery

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#218]
feedback: As you may see in the attached Url, the grid leaves a few blank pixel on the right hand side. Modula is inserted into an elementor block and I’ve already checked that there’s no margin or padding in any container elements.
Inspecting the images, I see that they are resized to a width that’s 1/2 pixels narrower than it should be. For instance, on a 1600px width, the images are not 800/400 pixel wide as I’d expect, but 798/399, so they don’t fill the container element.

Screenshot: https://gyazo.com/c0fc016a80c8d848bc6cef040f8874d6

**Comment by andreapelli** [comment]
Thank you for the quick reply

**Comment by vagu71** [comment]
Facing the same issue on the modula custom grid gallery.

**Comment by andyluak** [comment]
Could I have a url to the site that this problem is happening , because I can't replicate it  ?

**Comment by mplusb** [comment]
https://www.sunrisefilmproduction.com/wp/lord-of-the-bikes-v2/

**Comment by andyluak** [comment]
@mplusb thank you

**Comment by razvanaldea89** [comment]
Seems like this problem occurs when gallery type is `custom-grid` and  gutter is set to 0
