### ISSUE TITLE
Sorting metabox should be a "carousel"

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#223]
The sorting metabox upsell has the highest visibility. We should use this spot to "rotate" multiple upsells, based on the most proeminent features of Modula.

**Comment by giucu91** [comment]
We need to add this in order to add upsell for Modula Albums

**Comment by cristianraiber** [comment]
Looks great @razvanaldea89 .

Can we make the sorting metabox look like this, please? 

<img width="313" alt="image" src="https://user-images.githubusercontent.com/7841556/72265529-553d6c00-3625-11ea-9aa6-60fbf52fe295.png">

**Comment by cristianraiber** [comment]
I just used CSS to hide the metabox title and collapse button, then I removed padding from `.postbox .inside`

The UL list could use a bit more styling though ...

**Comment by andyluak** [comment]
Tested. No issues

**Comment by giucu91** [comment]
@razvanaldea89 Can you please add some arrows or bullets, because our users will see only 1. It's hard to notice that box as a carousel.

WHat you think @cristianraiber ?

**Comment by cristianraiber** [comment]
@giucu91 - I had the same thoughts about it when this was implemented. Since I was the one who pushed for a pure CSS implementation, I wasn't sure it's doable.

**Comment by giucu91** [comment]
@razvanaldea89 please check if it is possible with pure css, if not, please close this issue.

**Comment by razvanaldea89** [comment]
Added 2 metaboxes for upsells. First with albums
