### ISSUE TITLE
There will be a width issue regarding our gallery and theme Twentytwenty

### ISSUE THREAD

**Issue by razvanaldea89** [MachoThemes/modula-lite#230]
The problem lies within the style.css at line `3510` regarding the `max-width:58rem;` . An option should be added ( to shortcode/ block  ) so that users can add a class to the gallery ( input or a select with classes in the case of the block ) . Twentytwenty classes could be used :
-.alignwide
-.alignfull
-.alignleft
-.alignright
-.is-style-wide

Or simply set a max-width that is equal to the `width` option

**Comment by andyluak** [comment]
Tested . Fix works
