### ISSUE TITLE
Gallery edit/previewer major bug cause

### ISSUE THREAD

**Issue by razvanaldea89** [MachoThemes/modula-lite#232]
Seems like the cause of this is enqueueing the packery.js even though custom-grid is not selected.

**Comment by cristianraiber** [comment]
@razvanaldea89 - can u fix?

**Comment by razvanaldea89** [comment]
Well, we will need to enqueue/remove the script based on what type of gallery type is selected.

**Comment by razvanaldea89** [comment]
So...maybe save options with ajax and refresh the page when the user changes the gallery type?

**Comment by cristianraiber** [comment]
@giucu91  - pareri?

**Comment by giucu91** [comment]
@razvanaldea89 imi poti da un screen sa vad si eu despre ce e vorba ?
