### ISSUE TITLE
Modula block -- if first -- messes up other plugins' shortcodes

### ISSUE THREAD

**Issue by ElectricFeet** [MachoThemes/modula-lite#247]
Hi there! Looks like I've found a bug.

I'm using Modula Lite on a site (I'm also a Modula Pro customer on another site). I am using two plugins -- [Opening Hours](https://wordpress.org/plugins/wp-opening-hours/) and [Content Views](https://wordpress.org/plugins/content-views-query-and-display-post-page/) -- that use shortcodes to display their content (so I place them in shortcode blocks in the editor).

With Modula activated, the shortcodes don't work -- they display the text of the shortcode. 

For example, leaving only the Opening Hours plugin active:

- When Modula is **not** active, my page displays:
<img width="360" alt="Screenshot 2019-12-28 at 21 37 54" src="https://user-images.githubusercontent.com/6003638/71549235-51211580-29ba-11ea-962f-5138f22872d3.png">

- When Modula **is** active, my page displays:
<img width="232" alt="Screenshot 2019-12-28 at 21 37 24" src="https://user-images.githubusercontent.com/6003638/71549233-3ea6dc00-29ba-11ea-828c-ac61ee910068.png">

The same is true for the Content Views plugin -- content shows when Modula is not active, but the shortcode displays when Modula is active. Which leads me to conclude that this is definitely a Modula issue, not the plugins. 

I also swapped themes, to rule out any theme issues, but the problem persists.
 
Any idea what might be causing this?

**Comment by ElectricFeet** [comment]
OK, more detail after a lot of testing:

- With a Modula shortcode in a Gutenberg **shortcode block**
  - All is fine (phew, I have a workaround!).

- With a Modula gallery in a Gutenberg **Modula block**
  - If I use the Modula block in a page and follow it with other plugins' shortcodes, the other plugins' shortcodes **don't** get interpreted (they output as text, as shown above).

  - If I use shortcodes in a page, but the Modula block is **below** other plugins' shortcodes, the shortcodes **do** get interpreted (they show their content).

**Conclusion:** 
There's something wrong with the Modula Gutenberg block that causes it to stop other shortcodes on the page being interpreted (maybe filtering them / sanitizing them to text somehow?).

(All tested on WP 5.3.2, using TwentySeventeen or OceanWP, with plugins: Modula;  [Opening Hours,](https://wordpress.org/plugins/wp-opening-hours/); and [Content Views](https://wordpress.org/plugins/content-views-query-and-display-post-page/). I don't think that the choice of plugins is relevant: it happens with either or both active. (And just as an extra check, I deactivated them both and activated [Metaslider](https://wordpress.org/plugins/ml-slider/) to see if it produced the same results &mdash; and it did.))

**Comment by giucu91** [comment]
@ElectricFeet thank you for your feedback. You can modify Modula on your website like here : https://github.com/MachoThemes/modula-lite/commit/b0e40a4a5c6cae7de56ad1c8bc84cbf18943c37c

We will make an update next week.

**Comment by ElectricFeet** [comment]
@giucu91 I just updated and can confirm that my other shortcodes are now working fine on the same page. Thanks for the speedy fix!
