### ISSUE TITLE
Add numbers in front of hover effects in the select dropdown

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#256]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/7841556/71818569-0fffc400-3092-11ea-9bbe-fe21868a5293.png">

**Comment by cristianraiber** [comment]
It will make it easier for users to remember which effect they've tested. Also, easier to report it to support ( "I used hover effect number 19, etc)

**Comment by razvanaldea89** [comment]
Moved this in 2.2.4 because already implemented in branch 2.2.4 . And is working ok

**Comment by razvanaldea89** [comment]
Working ok on PRO version also.

**Comment by cristianraiber** [comment]
Nice work everyone 👏

**Comment by andrei-l-cristea** [comment]
confirmed, this works properly.
