### ISSUE TITLE
Loading effects metabox section should get a preview too (somehow)

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#257]
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/7841556/71818673-44738000-3092-11ea-8584-5a68d563fa3f.png">

**Comment by cristianraiber** [comment]
Right now it's impossible to see how these sliders impact the hover effects without saving, going into a new tab, refreshing the page.

**Comment by giucu91** [comment]
We can make something like this : https://daneden.github.io/animate.css/

**Comment by cristianraiber** [comment]
Also, I think we should replace the sliders here with number input type fields.

**Comment by cristianraiber** [comment]
@razvanaldea89 - need to display the active social icons as well as their font-size and color here too

**Comment by razvanaldea89** [comment]
@giucu91  Any opinion on how many rows? 1 would be enough, but with 2 the user can better understand the loading effect.

**Comment by giucu91** [comment]
2 rows with 3 images each. If @cristianraiber thinks it’s better with 2 image, 2 should be.

**Comment by cristianraiber** [comment]
yep, 2 x 2 I think looks better

**Comment by giucu91** [comment]
This is not working in Modula Lite

**Comment by giucu91** [comment]
Load in view should be the last option also with Modula PRO activated
