### ISSUE TITLE
Modula Uninstall suggestions

### ISSUE THREAD

**Issue by andrei-l-cristea** [MachoThemes/modula-lite#265]
1. It would be best to simply allow users to uninstall the plugin from the Plugins section without keeping the sub-menu item. It's kinda confusing to have users go to the sub-menu, make all selections, then go to the Plugins section and start the uninstall process.
2. The modal window from the Plugins section cannot be closed, we should add an X button, or Back. Also the modal window should be closed when the user clicks outside the box.
3. We should add a global option, like "Delete All data" so that the user can select everything with one click.
4. We should add a small description under each option so that users can better understand what they are actually removing.

**Comment by razvanaldea89** [comment]
Also, add a 'loading' icon after clicking 'uninstall' so that the users know the uninstall process is working
