### ISSUE TITLE
"Extensions" menu entry colouring to green not doing it right

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#269]
Right now, it looks like we're applying a green colour on the last link in the menu entry for Modula. However, there are plugins that "extend" that menu area and steal the green color from the "Extensions" link. 

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/7841556/72324639-1276a500-36b4-11ea-8550-a1ed786346d7.png">

**Comment by cristianraiber** [comment]
The Re-order menu entry is being added by a plugin similar to SCPO.

**Comment by razvanaldea89** [comment]
This should already have a fix in branch 2.2.4

**Comment by andyluak** [comment]
Tested and doesn't happen anymore .
