### ISSUE TITLE
Problems with Lightbox

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/modula-lite#27]
We need to find a solution for :

- Page Builders because some don't include the lightbox script that is enqueued from the shortcode
- Other plugins that use the same scripts as us ( LightBox )

**Comment by cristianraiber** [comment]
Page builder components:

- Elementor
- Visual Composer
- Gutenberg (future)
- Beaver Builder

**Comment by giucu91** [comment]
@razvanaldea89 we need to prefix fancybox.

**Comment by razvanaldea89** [comment]
Fancybox was prefixed. Will close this
