### ISSUE TITLE
Design bug with modula shortcode copy box

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#270]
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/7841556/72325051-f7f0fb80-36b4-11ea-9ef5-2858c2bc70f3.png">

**Comment by cristianraiber** [comment]
Analytics plugin used in this client's example: 

- https://wordpress.org/plugins/google-analytics-dashboard-for-wp/
- Also, Yoast SEO

**Comment by razvanaldea89** [comment]
For testing this the standalone modula needs to be activated

**Comment by razvanaldea89** [comment]
Moved this to milestone 2.2.4 as it has a fix in there

**Comment by andrei-l-cristea** [comment]
This is displayed properly now.
