### ISSUE TITLE
Review Modula Migrate

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#271]
https://github.com/machothemes/modula-importer

**Comment by ElectricFeet** [comment]
Not sure if you want help from the community at large, or within your team. If the former, the link above doesn't work.

**Comment by cristianraiber** [comment]
@ElectricFeet - it's actually for our team to take a look :) The repository was set to private, but I've now gone ahead and set it to public, since it'll be merged into Modula LITE anways. 

Feel free to download and test it. Right now, it should be working with: 
- Envira Gallery
- Final Tiles Grid Gallery
- NextGen Gallery
- WordPress native galleries
- Photoblocks

**Comment by ElectricFeet** [comment]
Ah. Not what I thought it was. I thought it was an importer/exporter of parameters etc that would make a gallery re-usable elsewhere, whereas this is presumably for new customers converting galleries from other plugins/core.

Great idea to make it easy for new users!

**Comment by cristianraiber** [comment]
@ElectricFeet - the feature you're looking for is actually there :) Just head over to tools -> Export or Tools -> Import on the new site. That's it there is to it :)

**Comment by giucu91** [comment]
I'll close this, Modula Migrate was released in 2.2.7

**Comment by cristianraiber** [comment]
@ElectricFeet - with Modula 2.2.7 we've actually added a sub-menu entry where you can Import/Export Modula galleries across multiple URLs
