### ISSUE TITLE
Gallery loading animations don't work if further down the page

### ISSUE THREAD

**Issue by ElectricFeet** [MachoThemes/modula-lite#273]
I have a gallery quite a long way down a page. When the gallery comes into view, the loading animations have already loaded, so it looks a bit boring.

Is it possible to have them load when they come into view, as for instance the [Blocks Animation](https://wordpress.org/plugins/blocks-animation/) plugin ([also here on github](https://github.com/Codeinwp/blocks-animation)) does?

**Comment by cristianraiber** [comment]
@ElectricFeet - could we get your gallery's URL, please?

**Comment by ElectricFeet** [comment]
Hi @cristianraiber It's not live yet. It should be in the next couple of weeks, at which point, I'll post it.

**Comment by ElectricFeet** [comment]
@cristianraiber There you go: maroncelli.dental

I'll be moving it to a new host over the weekend, so it may be unavailable Sat afternoon - Sun evening. So it's there now and should again (ha!) be available Monday.

**Comment by ElectricFeet** [comment]
After a finger-biting weekend counting the hours while email records refused to propagate, it's all live on [maroncelli.dental](maroncelli.dental) again.

**Comment by ElectricFeet** [comment]
@cristianraiber Don't know how Github managed to garble that link: it's fine in the source. Let's see if this works:

maroncelli.dental

The Modula gallery is half way down.

**Comment by ElectricFeet** [comment]
OK, this is now further complicated, as I've updated to Modula 2.2.4.

Now all the animations _above_ the gallery have stopped working (apart from the main after-header image, which is added earlier in php, not in the page itself).

If Modula is deactivated, all the animations work fine. But if it's active, then all the animations _before_ Modula stop working. Specifically, every column block below the main image has a class of "animated fadein", but this no longer works if it is before the modula gallery on the page.

So what happened in 2.2.4?

**Comment by cristianraiber** [comment]
@ElectricFeet - it looks like a fix for your issue is incoming :) Keep a close eye out for v2.2.7 of Modula.

**Comment by ElectricFeet** [comment]
Great! Look forward to it :)
