### ISSUE TITLE
Thumbnails Settings Not Taking Effect

### ISSUE THREAD

**Issue by vagu71** [MachoThemes/modula-lite#277]
There is a setting for Thumbnail size in the backend. This setting works only uptill the image in the backend is dragged and resized. Once that is done, no matter what the size, the frontend will show the actual image in the grid. If the images are say 2000x2000 in size, it will load the actual big images on the grid and in the anchor. The thumbnail setting in the backend appears to be redundant.

**Comment by giucu91** [comment]
@vagu71 can you give us a link where to see this behaviour ?

**Comment by giucu91** [comment]
I'll close this issue until @vagu71 responds.
