### ISSUE TITLE
lightbox caption

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#285]
the caption no longer displays in the lightbox.
It should: https://modula.helpscoutdocs.com/article/190-modula-lightbox-styles

**Comment by mplusb** [comment]
+1

**Comment by razvanaldea89** [comment]
Seems like it is displayed in the lightbox but only if image has description/caption added in Media Library

**Comment by andyluak** [comment]
The issue doesn't happen on the latest version on master . Tested with 2.2.4 and it does happen.

**Comment by razvanaldea89** [comment]
Can confirm what @andyluak says. Will close this.
