### ISSUE TITLE
Remove/enhance sliders on UI for setting font sizes

### ISSUE THREAD

**Issue by ElectricFeet** [MachoThemes/modula-lite#286]
Generally, when setting a font size (for captions / titles etc), we have a number in mind. Trying to slide a slider to enter this exact number is difficult and time consuming.

Sliders are generally only useful in a UI where you can see the effect of what you are doing. So you can, for instance, reduce opacity / brightness / saturation etc. of a colour and see the effect it has. Sliders can also be useful for setting scaling/zooming factors (as used in Modula for hover scaling etc), as it gives the the user a sense of "how far along the scale" they are.

In the case of a font size in a Modula gallery,  there is no visible feedback (nor is it needed) and there is no utility in knowing where 13px is on a scale of 0px to 100px.

**Suggestion 1 (best):**
Remove the sliders and just have a text box.

**Suggestion 2 (only if you really don't like suggestion 1):**
At least allow us to _also_ enter the number manually alongside the slider. The text field is currently read-only, so cannot be changed by hand.

I prefer suggestion 1, for reasons given above.

Both solutions would also allow copy/pasting values, which can save a lot of time when changing lots of galleries.

**Comment by cristianraiber** [comment]
@ElectricFeet - this is actually a really good suggestion!

**Comment by cristianraiber** [comment]
@ElectricFeet - just had a chat with one of our developers. This will be implemented in our next update :)
