### ISSUE TITLE
Setting title/font size to 0 doesn't default to theme as indicated

### ISSUE THREAD

**Issue by ElectricFeet** [MachoThemes/modula-lite#287]
The tooltip on "_Caption Font Size_" and "_Title Font Size_" (in the "Captions" tab) says:

> The title [ or caption ] font size in pixels (set to 0 to use the theme defaults).

However, setting the font size to 0 actually sets it to 0px, not the theme default.

**Comment by cristianraiber** [comment]
@ElectricFeet - thanks for reporting this, we'll fix it ASAP

**Comment by andyluak** [comment]
The problem doesnt happen anymore .

**Comment by razvanaldea89** [comment]
Doesn't happen for title but happens for caption

**Comment by razvanaldea89** [comment]
We also have to change from modula.min.css, because it overwrites the theme

**Comment by razvanaldea89** [comment]
Last comment,  https://github.com/WPChill/modula-lite/commit/2c6ea0d5b82ff6c750133a960d4fd3b5ddff6416, was meant for issue 287 from Modula PRO
