### ISSUE TITLE
Open 'media library' directly when you click on 'select from library'

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#291]
<img width="207" alt="image" src="https://user-images.githubusercontent.com/7841556/74026739-7472b380-49af-11ea-98ea-29e4ae9de990.png">

**Comment by cristianraiber** [comment]
<img width="290" alt="image" src="https://user-images.githubusercontent.com/7841556/74026750-7e94b200-49af-11ea-8768-ea072fdacc65.png">

**Comment by cristianraiber** [comment]
Right now, it's defaulting to "Upload files" tab instead of "Media Library"

**Comment by ElectricFeet** [comment]
I just tried this and it went straight to the library for me. Maybe it goes to where you were last?

**Comment by cristianraiber** [comment]
@ElectricFeet - huh, that's an interesting observation. Will test this and report back :)

**Comment by cristianraiber** [comment]
@ElectricFeet - it seems like you're right about this one. Would be great though to "force" the initial opening.
