### ISSUE TITLE
Share via email 

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#292]
Another social sharing option: email

**Comment by razvanaldea89** [comment]
Think here we should put 2 text inputs for translations ( `Here is the link to the image` and `Here is the link to the gallery` ) . @giucu91 @cristianraiber @andyluak any thoughts on this one?

**Comment by cristianraiber** [comment]
+1

**Comment by razvanaldea89** [comment]
Translation inputs don't save ok

**Comment by andyluak** [comment]
Share via email works ok on normal and pro hover effects . The fields sanitize properly .
