### ISSUE TITLE
scrolling issue

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#298]
when you open the lightbox it scrolls the page back to top
- check on Firefox
You can see it [here](https://wagnerbusato.com.br/).

**Comment by cristianraiber** [comment]
Can confirm this issue

**Comment by ElectricFeet** [comment]
Yup, I was just about to report this. V annoying when opening pages in different tabs.

**Comment by cristianraiber** [comment]
We'll get this fixed too!

**Comment by razvanaldea89** [comment]
Seems like the problem is from the "back button" functionality recently introduced. This also, in certain cases, prevents users to go back to previous page.

**Comment by ElectricFeet** [comment]
My themes have a “back to top” button on the pages. Is this a conflict?  

What is the “back button” in modula?

**Comment by razvanaldea89** [comment]
@ElectricFeet it is a problem, in certain cases, with the "back button" of the browser / mobile phone
