### ISSUE TITLE
Issues reported by users

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#30]
Issues below are related to Modula PRO, but in order to keep this ticket public, I've posted them here:

---

– the ‘swipebox’ does not display captions on mobiles (although this option was selected). The other boxes do.
– on tablets, there appears an unwanted outline/shadowline around some of the images. On phones / desktop they are not visible (= according to my settings)
– hitting the ‘back’ button in a lightbox brings me back to a previous page – this is not logic. It should bring be back to the page where I opened the lightbox.
– sporadically, the lightbox seems to load wrongly and just one still picture appears. After reload, the lightbox works OK.
– Although I bought Pro, the Lite version is still visible in my WP dashboard after the upgrade. I can not remove the previous Lite version. Worse – they are both called ‘Modula’ in dashboard, without Lite or Pro extension.
– Lightgallery displays arrows and some others elements that fade away on mobiles after 5 secs. However, this happens only with the first image. The elements stay visible on all next images and do not fade. I consider this to be a bug. (tested on phone / tablet, Chrome)

**Comment by cristianraiber** [comment]
More details, here: https://wordpress.org/support/topic/with-these-flaws-price-is-too-high/

**Comment by razvanaldea89** [comment]
- Plugins now called "Modula" for Lite and "Modula PRO".
- Lightgallery arrows on mobile fade away on all images after a certain amount of time, but they appear on touch or swipe
- Didn't have problems with lightbox loading
- Swipebox captions are not displayed due to the fact that swipebox hides the elements. Need to show them all the time in mobile

**Comment by andyluak** [comment]
- Swipebox captions appear top of the image for 5 sec . After they appear only by pressing the screen . Swipebox hides all the elements and displays the full image . 
- Could not recreate unwanted outline-shadownline on tablets
- Hitting back on a lightbox still bring you back to a previous page , not the page with the gallery.
- Could not recreate lightbox loading wrongly
- The Modula Pro and Modula Lite , appear under different names . This is issue is fixed.
- LightGallery arrows and other elements fade on all images . Working fine.
		All tests done on phone/tablet/laptop , Chrome .
