### ISSUE TITLE
issue with lightbox 2

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#309]
I am using Modula Lite and the option
lightbox2 came with it. Here is the link for the page that has the gallery
https://ursu.ca/campus-life/vip/

 the lightbox modal is pushed to bottom and only showed half of the image

![image](https://user-images.githubusercontent.com/26008574/75041031-6e5af780-54c4-11ea-8dad-22915318fbda.png)
![image](https://user-images.githubusercontent.com/26008574/75041052-77e45f80-54c4-11ea-89f5-69e631506747.png)

I think there is something wrong with the new update since before that the
lightbox2 worked as expected.

**Comment by razvanaldea89** [comment]
Seems to be a conflict with plugin wp-embeded-facebook. It has lightbox also, and enqueues CSS for it which conflicts with our

**Comment by giucu91** [comment]
lightbox2 will not be supported anymore. I'll close it.
