### ISSUE TITLE
Simplify lightboxes & links dropdown

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#310]
<img width="717" alt="image" src="https://user-images.githubusercontent.com/7841556/75135404-1998c600-56ea-11ea-8659-fd948a03a948.png">

**Comment by cristianraiber** [comment]
I think we should get rid of the titles "Link" and "Lightboxes" here. Also, using the title "Fancybox" has no relevance for users. We should change it to "Open images in a lightbox"

**Comment by giucu91** [comment]
@andyluak this it.s in singular-lightbox branch.
