### ISSUE TITLE
CTRL/CMD + S to save galleries 

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#317]
Maybe look into adding some keyboard shortcuts as well ¯\_(ツ)_/¯

**Comment by razvanaldea89** [comment]
Tested, working

**Comment by cristianraiber** [comment]
Maybe we should add a new metabox in the add/edit gallery page to mention our newly added kb shortcuts?

**Comment by razvanaldea89** [comment]
+1

**Comment by giucu91** [comment]
Maybe a tooltip next to the update gallery button ?

**Comment by cristianraiber** [comment]
I like @giucu91 's idea :) Let's make it happen!

**Comment by giucu91** [comment]
![image (5)](https://user-images.githubusercontent.com/7580330/83499866-b1b30200-a4c6-11ea-8ee5-898e3491d3bd.png)

**Comment by razvanaldea89** [comment]
This can be tested and closed if OK

**Comment by andyluak** [comment]
Shortcut works . Metabox looks good .
