### ISSUE TITLE
Disable social icons - should be enabled, ensure backwards compatibility

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#330]
![image](https://user-images.githubusercontent.com/7841556/77049477-d3751080-69d0-11ea-9fc7-fb83a886b3b3.png)

Right now, the toggle has Disabled as a title, but the value is enabled. It should be vice-versa.

**Comment by andyluak** [comment]
Backwards compatibility works.

**Comment by giucu91** [comment]
![image](https://user-images.githubusercontent.com/7580330/84370767-6644d600-abe1-11ea-8162-cf33d36002f2.png)

**Comment by giucu91** [comment]
![image](https://user-images.githubusercontent.com/7580330/84370881-8b394900-abe1-11ea-9f7e-058ab71e51b2.png)

VS

![image](https://user-images.githubusercontent.com/7580330/84370907-955b4780-abe1-11ea-8e1e-e680c6b557da.png)

Where it says that we need to disable all our icons by default ?

**Comment by razvanaldea89** [comment]
@giucu91  Rather than having all but the email icon enabled and the email disabled, on new galleries maybe it is best to disable all and let the user enable the socials he/she wants.

**Comment by giucu91** [comment]
@razvanaldea89 maybe but the backwards compatibility it's not working. Also the email icon is on by default !

**Comment by razvanaldea89** [comment]
Backwards compatibility issues has been fixed.
