### ISSUE TITLE
Conditional Fields

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/modula-lite#338]
![image](https://user-images.githubusercontent.com/7580330/77877450-7e51be00-725e-11ea-8ef1-8af713c5696c.png)

Enable Crop Images only if Image Size is Custom.
I don't have :  Row Height and Last Row Alignment

**Comment by razvanaldea89** [comment]
@giucu91 can u tell me what other add-ons u have installed? Seems to work ok for me.
