### ISSUE TITLE
Innegal padding

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/modula-lite#340]
![image](https://user-images.githubusercontent.com/7580330/77879123-67ad6600-7262-11ea-8703-249e40414991.png)

Top/Bottom: 12px
Left/Right: 24px

Also on 2/3/4/5/6 we don't need padding on edges( left/right )

**Comment by razvanaldea89** [comment]
Part 2 of the fix to this will be committed after or during the jquery-modula.js update.
