### ISSUE TITLE
hover effect 'none'

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#360]
https://wordpress.org/support/topic/great-plugin-that-gets-you-started/

 I could not turn the hover effect off, although I have set it to “None” it is still there.

When you choose the hover effect 'None' the caption and title will no longer be displayed, but the image will still have an effect on hover.

I fixed it using the following css. However, I think using “!important” is a sign of monkey patching. I think the “disable hovering” should be fixed.

```
.modula-item:hover img,
.modula .modula-items .modula-item.tg-loaded:hover img.pic
{
	opacity:1.0 !important;
}
```

Maybe the 'None' hover effect should have no effect at all.

**Comment by razvanaldea89** [comment]
Already rolled out
