### ISSUE TITLE
cannot change the number of columns on tablet

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#364]
screenshot:
![f78e15529f844d6c21d0b56155110641](https://user-images.githubusercontent.com/26008574/79948323-51b74d80-847c-11ea-8919-e61935ed3550.png)

**Comment by razvanaldea89** [comment]
Seems to be fixed

**Comment by razvanaldea89** [comment]
Hide responsive tab for columns type gallery with automatic columns type
