### ISSUE TITLE
autosuggest the url

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#368]
a way to use the standard "wordpress" link suggestion when using the "attachment url"? So the modula gallery has the option to fast link to a specific internal wordpress URL?
I want an "auto suggest" on the url field. So when you enter 3 letters an auto suggest of posts occurs.

https://secure.helpscout.net/conversation/1141901600/26093?folderId=1289779

For the URL field in metadata: https://modula.helpscoutdocs.com/article/186-add-links-to-images

**Comment by giucu91** [comment]
![image](https://user-images.githubusercontent.com/7580330/84368981-e7e73480-abde-11ea-9747-f7d112f08ef9.png)

VS

![image](https://user-images.githubusercontent.com/7580330/84369025-f5042380-abde-11ea-81e4-9a2cc9230842.png)

@razvanaldea89  @andyluak in the description it says **the standard wordpress link suggestion**

**Comment by razvanaldea89** [comment]
So fo the moment we leave it like so

**Comment by cristianraiber** [comment]
nope, this is not done properly.

**Comment by razvanaldea89** [comment]
@cristianraiber could you please a look at the new autosuggestion style?

**Comment by cristianraiber** [comment]
Looks great now!

**Comment by Florin415** [comment]
The arrow in the input is not centered on the middle :  
https://prnt.sc/t4y2u9
https://prnt.sc/t4y4hq

**Comment by razvanaldea89** [comment]
@Florin415 could you tell me what browser/OS are you using?

**Comment by razvanaldea89** [comment]
Seems like the problem was on Chrome ( Win10, didn't check macOS )
