### ISSUE TITLE
issue with the gutter

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#371]
When I set gutter to 1px, often the vertical gutters don't show, especially when the browser window is wide - tested in firefox
The vertical gutter between the poster and pics does not show when the browser window is at certain widths.
![Modula-Screengrab](https://user-images.githubusercontent.com/26008574/81277903-b1f1e600-905d-11ea-8cbb-c46985653608.jpg)
Screenshots from Chrome:
![Modula-Screengrab-Chrome-NarrowerWindow](https://user-images.githubusercontent.com/26008574/81277981-c46c1f80-905d-11ea-909f-26d1fd10c9cb.jpg)
![Modula-Screengrab-Chrome](https://user-images.githubusercontent.com/26008574/81277976-c33af280-905d-11ea-89ae-027936ec8e05.jpg)

I have figured out that if you zoom firefox or chrome in or out, the 1px margin will appear. On my screen, depending on the size of the browser window, the missing 1px margin will appear if I zoom in to 120% or zoom out to 67%. It's frustrating that it doesn't appear at 100% (or 90% or 110%)

https://secure.helpscout.net/conversation/1149105402/26328?folderId=1289779

**Comment by razvanaldea89** [comment]
Seems ok now
