### ISSUE TITLE
Remember metabox tab on gallery update

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#372]
When making setting changes in Modula's metabox tabs, and clicking on Update, the previously selected tab (the one I was working in) gets "lost". 

I think this should be persistent. When I click on update/save gallery, I should have active the tab I was working in.

**Comment by razvanaldea89** [comment]
Also remember tabs when exiting the gallery and reentering

**Comment by razvanaldea89** [comment]
Now remembers the tab no matter where the user goes.
