### ISSUE TITLE
Multiple Images

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/modula-lite#392]
when you have many images in a gallery (a clients has 150 for example), at first visit the gallery looks like : 

![image](https://user-images.githubusercontent.com/7580330/84752952-1aba6f80-afc7-11ea-903a-171a46b26380.png)

Config : 
![image](https://user-images.githubusercontent.com/7580330/84753263-708f1780-afc7-11ea-96eb-e7864475ed8e.png)

**Comment by razvanaldea89** [comment]
Problem seems to be fixed
