### ISSUE TITLE
Add an "edit gallery" below/above the link

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#397]
Right now, you use the shortcode to display the gallery. To "tie" the shortcode to a gallery, it means a lot of manual work. 

I think an "edit gallery" link, below the (frontend rendering of the) gallery, that leads to the actual gallery could help users a lot.

**Comment by cristianraiber** [comment]
Similar to how the "edit icon" for posts works right now

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/7841556/84880711-8f5bdf80-b095-11ea-8b06-323e7ba226aa.png">

**Comment by Florin415** [comment]
1. Talked to @giucu91 regarding the styling for the button , you could use edi post link to be sure the theme will style it . For the moment the button looks like this : https://prnt.sc/ugtq6v
2. If we have multiple galeries on the page and we will try to edit one of them, only the first edit button for the first gallery will work, the other edit buttons for the galeries will send us to random pages like in this example : https://drive.google.com/file/d/1S8Wmw0Hhd2oO5qVHSY685Z4kMUrNvuxf/view
