### ISSUE TITLE
Not working with Media Library Folders

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#398]
https://wordpress.org/support/topic/not-working-with-media-library-folders/

Get the plugin here for testing: https://secure.helpscout.net/conversation/1196151658/27994?folderId=1289779

Media Library Folders Pro helps site administrators to organize their media files by allowing them to create folders and move files. For inserting files into posts and pages, the plugin adds a folder tree to the Wordpress media uploader popup. When the user clicks on a folder in the tree, the media popup should refresh its contents which will display the files in the selected folder. Normally that is accomplished with

`wp.media.frame.content.get().collection.props.set({ignore: (+ new Date())});`

But with your gallery popup, this line will cause: TypeError: wp.media.frame is undefined. Hopefully, you guys can provide us with the code that we can use to refresh the contents of the popup when the Modula gallery is in use.

The code Media Library Folders Pro uses to refresh the media uploader contents can be found in the **media-library-plus-pro/js/mlfp-media.js** file.

**Comment by AJerm** [comment]
Thanks for posting this Mihaela! 
If you figure out a fix, if you could please post it here so I can manually apply it locally before your next update, as I've got 500 images that I've organised into folders and have ready to add to various galleries on one site. 
I'd love to be able to work on it over the weekend for my client if possible. 
Thanks :)

**Comment by AJerm** [comment]
Any chance someone has managed to look at this yet?

**Comment by andyluak** [comment]
@AJerm I found a solution to your problem . We were not able to fix it from our end because we have no action we can hook into . In `media-library-plus-pro/js/mlfp-media.js` at line 126 please add the following : 
`            if( typeof wp.media.frames.modula !== 'undefined' ){
              wp.media.frames.modula.content.get().collection.props.set({ignore: (+ new Date())});
            }
            if( typeof wp.media.frame.content.get() == null ) {
            wp.media.frame.content.get().collection.props.set({ignore: (+ new Date())});
            }
`

**Comment by AJerm** [comment]
You star, cheers @andyluak!

Will give that a go :)

**Comment by giucu91** [comment]
I'll close this.
