### ISSUE TITLE
404 undefined error

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#401]
getting:

undefined:1 Failed to load resource: the server responded with a status of 404 ()

and:

	Image (async)		
h.loadImage	@	modula-wf.js?ver=2.3.2:4
(anonymous)	@	modula-wf.js?ver=2.3.2:4
each	@	jquery.js?ver=1.12.4-wp:2
each	@	jquery.js?ver=1.12.4-wp:2
h.createCustomGallery	@	modula-wf.js?ver=2.3.2:4
h.reset	@	modula-wf.js?ver=2.3.2:4
(anonymous)	@	modula-wf.js?ver=2.3.2:4
setTimeout (async)		
h.onResize	@	modula-wf.js?ver=2.3.2:4
(anonymous)	@	modula-wf.js?ver=2.3.2:4
dispatch	@	jquery.js?ver=1.12.4-wp:3
r.handle	@	jquery.js?ver=1.12.4-wp:3

after update to the newest version. Hasn’t happened before.
https://wordpress.org/support/topic/404-undefined-error/

**Comment by giucu91** [comment]
fixed https://github.com/MachoThemes/modula-lite/commit/be00dd202da4256423a5530afbe4718fbe9da53b
