### ISSUE TITLE
modulaHelper is undefined

### ISSUE THREAD

**Issue by giucu91** [MachoThemes/modula-lite#403]
**Describe the bug**
modulaHelper is undefined
https://github.com/MachoThemes/modula-lite/blob/master/assets/js/jquery-modula.js#L622

**Comment by giucu91** [comment]
Also check this : https://github.com/MachoThemes/modula-lite/blob/master/assets/js/jquery-modula.js#L682

**Comment by razvanaldea89** [comment]
Old JS that is going to be erased.
