### ISSUE TITLE
Warning message not disappearing

### ISSUE THREAD

**Issue by Florin415** [MachoThemes/modula-lite#407]
**Describe the bug**
If we add more then 20 images when we add a new gallery ,we will receive the warning to upgrade to modula pro, but if we deselect some images the error still appears. If you go back to Select from library the warning message is still there.

**To Reproduce**
1. Go to 'Modula -> Add new ->Select from library '
2. Click on 'multiple images from your gallery (to add multiple images hold Ctrl and click the ones you want to add '
4. See error ' After we add 20 images the warning to upgrade to pro will appear : You exceeded the limit of 20 photos. You can remove an image or upgrade to pro'

**Expected behavior**
After we start to deselect some images the warning should disappear (also deselecting is done holding CTRL and clicking). Also check if the error message disappears if you go back to Select from library. 

**Screenshots**
https://www.screencast.com/t/DUnugllg8
https://www.screencast.com/t/H4XJZKRk

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* Modula Lite version:

**Comment by razvanaldea89** [comment]
Image limitation has been removed
