### ISSUE TITLE
Importer for FooGallery gallery plugin

### ISSUE THREAD

**Issue by razvanaldea89** [MachoThemes/modula-lite#409]
**Is your feature request related to a problem? Please describe.**
I want to import galleries from FooGallery plugin

**Describe the solution you'd like**
Add an importer for FooGallery plugin from where I can import their galleries into Modula.

**Comment by Florin415** [comment]
Tested the import for the galleries, used the recommended plugin from the Import/Export tab (WordPress Importer). but I could not import the galleries exported from the following plugins in Modula . As we can see in the screenshots we will have errors on each import.

Plugins used : 
Envira Gallery Lite -v 1.8.0
https://prnt.sc/tdat9z
https://prnt.sc/tdatmd

FooGallery -v 1.9.25
https://prnt.sc/tdamoi
https://prnt.sc/tdan7d

NextGEN Gallery -v 3.3.6
https://prnt.sc/tdbaab
https://prnt.sc/tdbapc

**Comment by Florin415** [comment]
After making 2 galleries with FooGallery -v 1.9.25 and I migrate them from FooGallery to Modula , it will create multiple times the same gallery : ( after creating galleries with FooGallery I deactivated the plugin ) 
https://drive.google.com/file/d/1KMb4AFHUnZMUKgjD35OKZwt00XqQwpTV/view

**Comment by Florin415** [comment]
Imported again the galleries created with the 3 plugins, after installing the master branch for Modula, the galleries where imported and it did not create multiple times the same gallery.
