### ISSUE TITLE
Default title 

### ISSUE THREAD

**Issue by Florin415** [MachoThemes/modula-lite#410]
**Is your feature request related to a problem? Please describe.**
If a user does not add a title to a Modula gallery , when he will try to add it to his page it will look like this :https://prnt.sc/tb2dwv

**Describe the solution you'd like**
It would be more user friendly if you don't add the title to the gallery to have a title added to you like "Unnamed" or something similar.

**Comment by razvanaldea89** [comment]
Seems ok

**Comment by razvanaldea89** [comment]
Translation for strings

**Comment by razvanaldea89** [comment]
Has commit https://github.com/MachoThemes/modula-lite/commit/eafa3b9820b13e223e17b552369e878d855cceb0
