### ISSUE TITLE
Migrate from FooGallery to Modula gutter issue

### ISSUE THREAD

**Issue by Florin415** [MachoThemes/modula-lite#411]
**Describe the bug**
Gutter option is not exported from FooGallery to Modula

**To Reproduce**
1. Make a gallery with FooGallery Version 1.9.25 , go to Gallery Settings and choose -> Masonry Image Gallery . After that choose to have no gutter to the gallery.
2. Migrate the gallery to Modula Lite 2.3.4 and go to the migrated gallery to edit it -> General -> and we can see that we will have a gutter . 

**Expected behavior**
If we migrated the FooGallery with no gutter, the Modula Gallery should not have one also. 

**Screenshots**
https://drive.google.com/file/d/1dfizMTkULo8nT__S4d1p9ky9FqnPBMLu/view

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [x] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [x] Tablet
- [x] Mobile
- [ ] Other 

#### Used versions
* WordPress version:  5.4.2
* Modula Lite version: 2.3.4

**Comment by Florin415** [comment]
Retested with the Modula Lite master branch , if you put in FooGallery 0 for example on the migration in Modula will keep the gutter still 0 and also if you put 20 for example on the migration the gutter will still be 20.

**Comment by razvanaldea89** [comment]
On retest works ok. I'll close this one.
