### ISSUE TITLE
Lazy Load not migrated from FooGallery

### ISSUE THREAD

**Issue by Florin415** [MachoThemes/modula-lite#416]
**Describe the bug**
If we have activated lazy load on a gallery created in FooGallery , it will not be enabled in Modula gallery
**To Reproduce**
1. Install FooGallary  Version 1.9.25, create a Image Viewer and select lazy load to be enabled. https://prnt.sc/te0nul
2. Migrate the gallery to Modula
3. Go in Modula -> the migrated gallery -> edit-> Speed Up and we will see that lazy load is disabled : https://prnt.sc/te0pys

**Expected behavior**
The option to be enabled.

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.4.2
* Modula Lite version: Master
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
Already pushed
