### ISSUE TITLE
Notice doesn't go away

### ISSUE THREAD

**Issue by razvanaldea89** [MachoThemes/modula-lite#417]
**Describe the bug**
After doing a fresh install or updating from Modula < 2.3.0, the notice with the new official lightbox for Modula can't be closed/dismissed on some of the pages of Modula ( settings page being one of them )

**To Reproduce**
1. Install fresh Modula
2. Go to settings page
3. Try to dismiss the notice

**Expected behavior**
The notice should go away.

**Screenshots**
![image](https://user-images.githubusercontent.com/44024114/87129494-19185a80-c29a-11ea-8efa-5ac7b5a0d877.png)

* Which addons do you have installed: 
- [x] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [x] Tablet
- [x] Mobile
- [x] Other 

#### Used versions
* Modula Lite version: 
* Modula PRO version: -

**Comment by razvanaldea89** [comment]
@andyluak  same procedure as #419

**Comment by andyluak** [comment]
Tested on fresh install. Notice goes away .
