### ISSUE TITLE
Arrows and close icon does not show

### ISSUE THREAD

**Issue by ttimot24** [MachoThemes/modula-lite#419]
**Describe the bug**
On my clean WP install the navigation arrows and close icons does not showing or too small,

**Expected behavior**
Change the default size, or add an option to be able to change it,

**Screenshots**
![kép](https://user-images.githubusercontent.com/10697800/87542913-063fc480-c6a4-11ea-84e4-bd6e36867622.png)

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Firefox
- [x] Chrome
- [x] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [x] Tablet
- [x] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.4.2
* Modula Lite version: 2.3.3
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
Hello @ttimot24 , could you be kind and tell us what theme/other plugins you are using? Just tested and seems OK, so maybe it is a theme/plugin conflict.

**Comment by ttimot24** [comment]
Hi @razvanaldea89,

I'm using Customify theme:
https://pressmaximum.com/customify/

Plugins I use (all up to date):
Carousel Slider
Contact Form 7
EditorsKit
Jetpack
Modula
Polylang

Thank you very much! :)

**Comment by razvanaldea89** [comment]
Yes, it seems to be a conflict with the theme, it overwrites some parts of the button CSS

**Comment by ttimot24** [comment]
Do you have any idea how can I solve this? Maybe if I add the whole button style to the custom css in modula with !important?

**Comment by razvanaldea89** [comment]
@ttimot24 you can try putting custom CSS in Appearance->Customize->Additional CSS so you won't have to put in every Modula Gallery the same CSS over and over again.

**Comment by ttimot24** [comment]
Hi!

Can you please release this fix? One of my production site really needs it. 

Thank you for the fix! :)

**Comment by razvanaldea89** [comment]
Hello @ttimot24 ,

I think in the next few days an update will be released containing this fix along with other small ones.

**Comment by razvanaldea89** [comment]
@andyluak Please take the fix commited in branch 2.3.4 and add it here.

**Comment by andyluak** [comment]
Arrows and close icons shows .

**Comment by ttimot24** [comment]
Hi!

Can you please release this version? As I see every issue is in tested status int this milestone.

Thank you!

**Comment by cristianraiber** [comment]
@ttimot24 Should be released sometime next week.
