### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by Florin415** [MachoThemes/modula-lite#420]
**Describe the bug**
On responsive devices when we try to create a gallery , some of the options exceeds the devices width 

**To Reproduce**
Try and create a gallery and when you are on the gallery options page try and use a responsive device (phone or tablet).

**Screenshots**
Phone ( landscape and portrait) : https://prnt.sc/tl287n
Ipad(landscape and portrait) : https://prnt.sc/tl1yu9

* Which addons do you have installed: 
- [x] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [x] Tablet
- [x] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.4.2
* Modula Lite version: 2.3.3
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
Will close this as it is same as #336
