### ISSUE TITLE
Upload image files not having a 20 images limit

### ISSUE THREAD

**Issue by Florin415** [MachoThemes/modula-lite#421]
**Describe the bug**
If we try to upload images using the "Upload Image Files" option it will allow us to upload more than 20 images.  We should have the same limit as in "Select From Library" with a similar warning.
**To Reproduce**
1. Try an create a new gallery
2. Click on "Upload Image files" (have more than 20 images that you want to upload" 

**Expected behavior**
It should restrict us to 20 images and also have a warning when we go over that limit.

**Screenshots**
https://drive.google.com/file/d/1P94sbQE-CV3x96JLZCQESl5GAcoSgVvg/view

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [x] Tablet
- [x] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 2.3.4
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment]
The limit will be removed. Will close this
