### ISSUE TITLE
Elementor compatibility issue

### ISSUE THREAD

**Issue by razvanaldea89** [MachoThemes/modula-lite#430]
**Describe the bug**
JS error `elementorFrontend.hooks is undefined` when editing page with Elementor

**To Reproduce**
1. Install Elementor and edit a page
2. Add the Modula Widget
3. Try to select a gallery

**Expected behavior**
Should display the selected gallery

**Screenshots**
![image](https://user-images.githubusercontent.com/44024114/90396729-64930500-e09f-11ea-925f-fde9cd31f222.png)

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.5
* Modula Lite version: 2.3.6
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by CRdeGraaf** [comment]
same issue on WP 5.5. get the following undefined error in console:
```
Uncaught TypeError: Cannot read property 'addAction' of undefined
    at HTMLDocument.<anonymous> (modula-elementor-preview.js?ver=2.3.5:3)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
    at Function.ready (jquery.js?ver=1.12.4-wp:2)
    at HTMLDocument.J (jquery.js?ver=1.12.4-wp:2)
```

gallery doesnt load, just shows an empty grey wrapper element.

broken line:
```elementorFrontend.hooks.addAction(...)```

this is the first action after loading the page, but as is with everything javascript, it should neatly be waiting in a callback waiting for all dependancies (elementor object) to load.

according to the [elementor api](https://developers.elementor.com/creating-a-new-widget/adding-javascript-to-elementor-widgets/) this is done by wrapping ./wp-content/plugins/modula-best-grid-gallery/assets/js/admin/modula-elementor-preview.js in:
```
jQuery( window ).on( 'elementor/frontend/init', () => {
...
});
````
and ofcourse dont forget to minify the file.
works properly now.

please include in next version.

**Comment by razvanaldea89** [comment]
Great work @CRdeGraaf

**Comment by razvanaldea89** [comment]
Already deployed
