### ISSUE TITLE
Elementor Plug in failed to load

### ISSUE THREAD

**Issue by KozyWozy** [MachoThemes/modula-lite#431]
**Describe the bug**
Hi I have been using #316  Elementor for a while now as a splash page for a client waiting for them to sign off in using the rest of your featurfes and build the full website so havn't signed up for pro yet.

Wordpress updated and then Elementor tried to update and came up with the follwoing "This plugin failed to load properly and is paused during recovery mode."

![Screen Shot 2020-08-18 at 8 47 18 am](https://user-images.githubusercontent.com/69824555/90451584-71f7d000-e12f-11ea-9a08-fde445d9b41a.png)

Not sure how you would reproduce this. I have no other plug ins activated and havn't started using Elementor in any big way just yet.

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [x] Tablet
- [x] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by cristianraiber** [comment]
@KozyWozy - this doesn't seem to be related to Modula though. Can you update Elementor if you de-activate Modula?

**Comment by cristianraiber** [comment]
@KozyWozy - could you please update to the latest Modula LITE version? We've released a fix for this.
