### ISSUE TITLE
Gallery filter, real time refresh bug

### ISSUE THREAD

**Issue by Linkinjil** [MachoThemes/modula-lite#433]
Hi, first of all, sorry for my english.

I'll try to explain my bug as best as possible.
I'm currently developping a website with a gallery page based on Modula including filter.
But currently, the filter use is working but images are spreding in a shitty way.

![Capture](https://user-images.githubusercontent.com/69955952/90725968-3ee54600-e2c1-11ea-9440-9911ab116c1f.PNG)

The only way I have to counter it now is to check the "Reload Page On Filter Click" on the Filter.
It works more or less then.

This website going to be online soon, is there a way to make this work properly?

Thanks

**Comment by razvanaldea89** [comment]
Hello @Linkinjil ,

Just tested on my install but seems to work fine. Could you tell me what versions of Modula LITE, Modula PRO and WordPress are you using? And what settings has the created gallery? Are there any errors in the browser console?

**Comment by Linkinjil** [comment]
@razvanaldea89 gonna try this morning.
Will stay you update ;)
