### ISSUE TITLE
Remove Google+ sharing as Google+ will be shutting down

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#44]

**Comment by giucu91** [comment]
Eu zic sa il scoatem cand nu o sa mai poti face nimic sau se plange primul client decat sa ne vina pe support ca nu mai are G+

**Comment by cristianraiber** [comment]
Yep, e mai buna abordarea asta.

**Comment by cristianraiber** [comment]
Your personal Google+ account is going away on April 2, 2019

**Comment by cristianraiber** [comment]
Save your Google+ content before March 31, 2019 

@giucu91 - in our next Modula update, we should remove G+
