### ISSUE TITLE
See LITE vs PRO difference upsell button doesn't link anywhere

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#45]
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/7841556/46799959-dd67fe00-cd5e-11e8-8f58-5c4bd89bcbac.png">

**Comment by giucu91** [comment]
Am adaugat link pe see Lite vs PRo dar pe Get Modula nu am pus pana nu avem site.
