### ISSUE TITLE
Feature request in the addons page doesn't do anything

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#49]

**Comment by cristianraiber** [comment]
@giucu91 - we can use this form: https://docs.google.com/forms/d/1ufCdC3FFLlKL6cXHslq_rEZMGoT0bIOX2_8b1zRmqvs/prefill

**Comment by giucu91** [comment]
@cristianraiber the link is not good.

**Comment by cristianraiber** [comment]
@giucu91 https://docs.google.com/forms/d/1ufCdC3FFLlKL6cXHslq_rEZMGoT0bIOX2_8b1zRmqvs
