### ISSUE TITLE
Add link per image

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#61]
https://wordpress.org/support/topic/link-to-another-page-5/

**Comment by giucu91** [comment]
Now it's posibile but you need to select Attachment page on Lightbox & Links setting.

**Comment by cristianraiber** [comment]
@giucu91 - we should add a notice / description next to this field in the modal pop-up stating this exact fact. That you need to select attachment page on `Lightbox & Links setting.`
