### ISSUE TITLE
Grid spacing issue

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#64]
![image](https://user-images.githubusercontent.com/7841556/48942828-b8ec6d80-ef29-11e8-8387-4d34f87964dd.png)
![image 1](https://user-images.githubusercontent.com/7841556/48942832-bb4ec780-ef29-11e8-9a64-a4f71a802b89.png)

**Comment by cristianraiber** [comment]
In a doua poza, am sters 2 imagini din previewer si a aparut placeholder-ul acela.

**Comment by giucu91** [comment]
We need to find a solution so we can remove resizesenzor.
