### ISSUE TITLE
Lacks widget

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#65]
We don't currently have a companion widget for the plugin. It looks like users can't figure out to place the shortcode inside a widget and would very much prefer a widget that allows them to select the gallery to display.

**Comment by razvanaldea89** [comment]
@cristianraiber  Actually there is a widget for Modula Gallery.

**Comment by cristianraiber** [comment]
@razvanaldea89 - really old ticket :) Probably, we got a widget added in the meantime, but no one updated this ticket.
