### ISSUE TITLE
Avada incompatibility

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#66]
Avada. Sticky header would not work when gallery shortcode is on page.

**Comment by mplusb** [comment]
Another issue with Avada:
The integrated gallery of Avada and the Modula Gallery did not play along. Once the plugin was activated, it destroyed all the existing galleries.

**Comment by mplusb** [comment]
screenshot with the error: https://gyazo.com/1b5fdb1eef6040a40052d0a5260228f3

**Comment by mplusb** [comment]
+1

**Comment by razvanaldea89** [comment]
Could you please give more details? Both sticky header and Avada gallery seem to work

**Comment by mplusb** [comment]
when Modula is active the native galleries of avada do not work.
Here is a screenshot with the error: https://gyazo.com/1b5fdb1eef6040a40052d0a5260228f3

**Comment by giucu91** [comment]
This was resolved in 2.2.7
