### ISSUE TITLE
Cache plugins compatibility

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#71]
- WP Fastest Cache
- WP Rocket
- WP Bullet
- Autoptimize

Let's make sure our plugin works properly with all of the above.

**Comment by mplusb** [comment]
tested and works with:
- WP Fastest Cache
- Autoptimize
- WP Rocket

I did not have WP Bullet in order to test

**Comment by giucu91** [comment]
I'll close this because WP Bullet it's not released.
