### ISSUE TITLE
LightBox improvements

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#81]
- automatic playback in the lightbox images in the form of slideshow
- fingers are not flipped through the pictures on the mobile version (aka: need to be able to use your finger to navigate through the images when opened in a lightbox)
- Lightbox on mobile devices is not visible if screen orientation is changed. Most likely it just doesn\'t reposition itself to a new screen orientation.

**Comment by razvanaldea89** [comment]
Slideshow is a pro add-on feature.
Swiping seems to work.
Lightbox on mobile issue will be issued a fix
