### ISSUE TITLE
Creative Gallery issue (one image is missing)

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#93]
![image 1](https://user-images.githubusercontent.com/7841556/49505415-66457680-f884-11e8-91a5-69ad2cae6eaa.png)
![image](https://user-images.githubusercontent.com/7841556/49505418-680f3a00-f884-11e8-80d2-54d59274b627.png)

**Comment by giucu91** [comment]
We didn't receive this in support forums so until then I'll close it.
