### ISSUE TITLE
Custom Grid spacing in the backend

### ISSUE THREAD

**Issue by cristianraiber** [MachoThemes/modula-lite#94]
This spacing doesn't reflect on the frontend, but it does on the backend. Users shouldn't be allowed to leave this space as it might confuse them.

**Comment by cristianraiber** [comment]
> 
<sub>[View in Slack](https://macho-themes.slack.com/archives/D0HM066QK/p1544004104015800)</sub>

**Comment by cristianraiber** [comment]
![image 2](https://user-images.githubusercontent.com/7841556/49506155-0b148380-f886-11e8-9161-9a39783e9c4a.png)

**Comment by mplusb** [comment]
seems fixed

**Comment by razvanaldea89** [comment]
Actually if we have fewer images we can drag & drop them with spaces between that could confuse the user.
![modula grid spacing](https://user-images.githubusercontent.com/44024114/63417488-10146580-c40a-11e9-8ff3-0626b8084a71.PNG)

**Comment by giucu91** [comment]
This it's not possible with packery at this point. I'll close this issue.
