### ISSUE TITLE
gutter issue

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/modula-lite#95]
When I set the Gutter to 0 the gallery doesn’t appear on the page at all, there’s just a big white area where the images should be. When I inspect element the images are all there on the page but they seem to have width set to 0px, and both top and left are set to 0px too. When I set the gutter to 5px the images appear fine, but I don’t want them to display with any space between them.

**Comment by mplusb** [comment]
this still exists

**Comment by giucu91** [comment]
It's fixed.
